# TODO: Delete either yarn or npm section
name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1
# NPM
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run test
